# theme = "sonokai"
# theme = "nord-night"
theme = "everforest_dark"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = "bar"
select = "underline"

# [editor.file-picker]
# git-ignore = false
# git-global = false

[editor.soft-wrap]
enable = true

[editor.indent-guides]
render = true

[editor.whitespace.render]
newline = "all"
space = "none"
tab = "none"

[editor.whitespace.characters]
newline = "󱦳"
# newline = "󱞣"

[editor.file-picker]
hidden = false

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

[keys.select]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"

