[[language]]
name = "git-config"
file-types = ["gitconfig"]

[[language]]
name = "git-ignore"
file-types = ["gitignore"]

[[language]]
name = "bash"
file-types = [{glob="zshrc"}]

[language-server.metals]
command = "metals"
args=[
  "-Dmetals.verbose=on",
  "-Dmetals.loglevel=debug",
  "-Dmetals.pc.debug=on",
]

[language-server.metals.config]
compilerOptions.overrideDefFormat = "unicode"
isHttpEnabled = true
debuggingProvider = true
icons = "unicode"
# inlineDecorationProvider = true

[language-server.jdtls]
command = "jdtls"
args=[
  "-Djava.format.settings.url='file:~/.config/styleguide/eclipse-java-google-style.xml'",
  # "-data", "$TMPDIR/jdtls-workspace",
  "-Djdt.ls.debug=true",
]
