[[language]]
name = "git-config"
file-types = ["gitconfig", { glob = ".gitmodules" }, { glob = ".gitconfig" }, { glob = ".git/config" }, { glob = ".config/git/config" }]

[[language]]
name = "git-ignore"
file-types = ["gitignore", { glob = ".gitignore_global" }, { glob = "git/ignore" }, { glob = ".ignore" }, { glob = "CODEOWNERS" }, { glob = ".config/helix/ignore" }, { glob = ".helix/ignore" }, { glob = ".*ignore" }]

[[language]]
name = "bash"
file-types = [ "zsh", {glob="zshrc"} ]

[[language]]
name = "python"
# language-servers = [ "pyright" ]
language-servers = [ "basedpyright" ]

[language-server.kotlin-language-server]
config = {kotlin.compiler.jvm.target = 21}

[language-server.metals]
command = "metals"
args=[
  "-Dmetals.verbose=on",
  "-Dmetals.loglevel=debug",
  "-Dmetals.pc.debug=on",
]

[language-server.metals.config]
compilerOptions.overrideDefFormat = "unicode"
icons = "unicode"
inlineDecorationProvider = true
# debuggingProvider = true

# [language-server.jdtls]
# command = "jdtls"
# args=[
#   "-Djava.format.settings.url='file:~/.config/styleguide/eclipse-java-google-style.xml'",
#   # "-data", "$TMPDIR/jdtls-workspace",
#   "-Djdt.ls.debug=true",
# ]
